# A sample Gemfile
source "https://rubygems.org"

gem "mysql2"
gem "dalli"
gem "redis"
gem "pg"
gem "activerecord", require: 'active_record'
gem "mongo"
gem "bson_ext"

gem "slop"
gem "pry"
gem "descriptive_statistics"
